name: Build and Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  windows-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
    steps:
      - uses: actions/checkout@v2
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ matrix.os }}-QtCache
      - name: Install Qt with options
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.1
          tools: 'tools_ifw,4.0,qt.tools.ifw.40 tools_openssl_x64,1.1.1-4,qt.tools.openssl.win_x64'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - name: Install necessary Chocolatey packages
        run: |
          choco install jom -y --no-progress
          choco install openssl -y --no-progress
        shell: cmd
      - uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey
          key: ${{ runner.os }}-chocolatey-${{ matrix.os }}-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            ${{ runner.os }}-chocolatey-${{ matrix.os }}-
            ${{ runner.os }}-chocolatey-
      - name: Make project and build installer
        run: |
          echo "Building project..."
          call "%programfiles(x86)%\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          qmake "CONFIG+=release"
          jom
          echo "Deploying binary dependencies..."
          set TIB_RELEASE_BUILD=%cd%\release\github-action-test.exe
          set TIB_DEPLOY_DIR=%cd%\deploy\windows
          set TIB_PKG_DATA_DIR=%TIB_DEPLOY_DIR%\packages\name.SMR76.github_action_test\data
          set TIB_INSTALLER_FILE=github_action_test.exe
          copy "%TIB_RELEASE_BUILD%" "%TIB_PKG_DATA_DIR%"
          windeployqt --release --qmldir . "%TIB_PKG_DATA_DIR%\github-action-test.exe"
          echo "Adding OpenSSL DLLs..."
          set OPENSSL_BIN_DIR=%ProgramFiles%\OpenSSL-Win64\bin
          copy "%OPENSSL_BIN_DIR%\libcrypto-1_1-x64.dll" "%TIB_PKG_DATA_DIR%"
          copy "%OPENSSL_BIN_DIR%\libssl-1_1-x64.dll" "%TIB_PKG_DATA_DIR%"
          echo "Building installer..."
          dir "%TIB_PKG_DATA_DIR%"
          set PATH=%PATH%;%RUNNER_WORKSPACE%\Qt\Tools\QtInstallerFramework\4.0\bin
          binarycreator -c "%TIB_DEPLOY_DIR%\config\config.xml" -p "%TIB_DEPLOY_DIR%\packages" %TIB_INSTALLER_FILE%
        shell: cmd
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Windows (Installer)
          path: github_action_test.exe
