name: CI build

on:
  push:
#     tags:        
#       - v*

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 5.15.2
          
        platform:
          # - gcc_64
          # - android
          # - msvc2019
          # - msvc2019_64
          # - mingw81_32
          # - clang_64
          - mingw81_64

        include:
#           - platform: gcc_64
#             os: ubuntu-latest
#           - platform: android
#             os: ubuntu-latest
#           - platform: msvc2019_64
#             os: windows-latest
#           - platform: msvc2019
#             os: windows-latest
#           - platform: mingw81_32
#             os: windows-latest
#             ver: win32_mingw81
#           - platform: clang_64
#             os: macos-latest
          - platform: mingw81_64
            os: windows-latest
            arch: win64_mingw81
            
    runs-on: ${{matrix.os}}
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - uses: actions/setup-python@v1
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.0
        with:
          version: ${{ matrix.version }}
          arch:    ${{ env.arch }}
          extra:   --external 7z
          
#       - uses: Skycoder42/action-setup-qt@master
#         id: qt
#         with:
#           host: ${{matrix.os}}
#           version: ${{matrix.version}}
#           platform: ${{matrix.platform}}
#           packages: qt.tools.ifw.32
#       - name: Find String
#         id: fstr
#         uses: nguyenvanuyn96/str-find-action@master
#         with:
#           find: "^.*qml"
      
      - name: qmake
        run: |
          qmake CONFIG+=install_ok QT_PLATFORM=${{matrix.platform}} "QT_TOOL_PATH=${{github.workspace}}/Qt/Tools" github-action-test.pro
#          ${{steps.qt.outputs.make}} qmake_all
      - name: qmake all and make 
        if: ${{matrix.platform}} == mingw81_64
        run: |        
          "${{github.workspace}}/Qt/Tools/${{matrix.platform}}/bin/mingw32-make.exe" qmake_all
          "${{github.workspace}}/Qt/Tools/${{matrix.platform}}/bin/mingw32-make.exe" -j8
#       - name: make module
#         run: |
#           ${{steps.qt.outputs.make}}
#           ${{steps.qt.outputs.make}} INSTALL_ROOT="${{steps.qt.outputs.installdir}}" install
      - name: upload module to releases
        uses: Skycoder42/action-upload-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          directory: ${{steps.qt.outputs.outdir}}
          platform: ${{matrix.platform}}
          asset_name: nut-${{matrix.platform}}-${{matrix.version}}
          tag: ${{github.ref}}
          overwrite: true
#   deploy:
#     if: startsWith(github.ref, 'refs/tags/')
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#         with:
#           submodules: recursive
#           path: source
#       - uses: actions/setup-python@v1
#       - uses: Skycoder42/action-deploy-qt@master
#         with:
#           token: ${{secrets.GITHUB_TOKEN}}
#           version: 5.15.2
#           host: ${{secrets.SSHFS_HOST}}
#           key: ${{secrets.SSHFS_KEY}}
#           port: ${{secrets.SSHFS_PORT}} 
